agent:
trainer:
  trainer_cls: 'DQN'
  policy: "MlpPolicy"
  learning_rate: 1e-4
  batch_size: 512
  gamma: 0.95
  buffer_size: 20000
  learning_starts: 0
  target_update_interval: 3000
  verbose: 0 
  tensorboard_log: "./tmp/tensorboard/"
  total_timesteps: 2e6
  progress_bar: True
  device: "cuda"
  policy_kwargs: 
    net_arch: [256, 256]
env:
  id: "LayerEdgeDynamicEnv-v0"
  storage_type: "PriorityStorage"
  prefix: "popularity"