agent:
trainer:
  trainer_cls: 'PPO'
  policy: "MlpPolicy"
  learning_rate: 3e-4
  n_steps: 1024
  batch_size: 8192 # env_size * n_steps
  n_epochs: 16
  policy_kwargs: 
    net_arch: 
      pi: [512, 256, 128]
      vf: [512, 256, 128]
  gamma: 0.95
  verbose: 0 
  tensorboard_log: "./tmp/tensorboard/"
  total_timesteps: 1e7
  progress_bar: True
  device: "cpu"
  # 3. PPO特有参数
  clip_range: 0.2        # 限制策略更新步长
  ent_coef: 0.05        # 提高探索度
env:
  id: "LayerEdgeDynamicEnv-v0"
  is_predeploy: True       # 是否预部署
  predeploy_degree: 1      # 提前预部署几个？
  prefix: "interval-100-predeploy-1"
